server:
  port: 8080
  servlet-path: /admin

management:
  security:
    enabled: false

cxf:
  path: /
  servlet.init:
    service-list-path: /info
  jaxrs:
    component-scan: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
    # default is /info and /health but our management api is under /admin
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    # make faster to register and delete instances from eureka registry
    # how often send heartbreak
    leaseRenewalIntervalInSeconds: 1
    # how long to wait after heartbreak is not sent to expire the instance
    leaseExpirationDurationInSeconds: 2