server:
  port: 8080

management:
  security:
    enabled: false

cxf:
  jaxrs:
    component-scan: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

#    ## UNCOMMENT THIS TO MAKE FASTER TO REGISTER AND EXPIRE INSTANCES IN EUREKA
#    ## Default settings are recommended by Spring on production
#    ## how often heartbreak is sent. Default is 30s
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    ## how long to wait after heartbreak is not sent to expire the instance. Default is 90s
#    leaseExpirationDurationInSeconds: 2