server:
  port: 8888

management:
  security:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maciejkujawski/spring-cloud-jaxrs-cxf-getting-started.git
          searchPaths: ['/config/','/config/{application}']
          clone-on-start: true

