server:
  port: 8888

management:
  security:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
#    ## UNCOMMENT THIS TO MAKE FASTER TO REGISTER AND EXPIRE INSTANCES IN EUREKA
#    ## Default settings are recommended by Spring on production
#    ## how often heartbreak is sent. Default is 30s
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    ## how long to wait after heartbreak is not sent to expire the instance. Default is 90s
#    leaseExpirationDurationInSeconds: 2

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maciejkujawski/spring-cloud-jaxrs-cxf-getting-started.git
          searchPaths: ['/config/','/config/{application}']
          clone-on-start: true

